# Day 22 (2023-12-22), Exercise a

In [4]:
with open("input_22_dummy.txt", "r") as fh:
    lines = fh.readlines()
# Remove \n characters
lines = [l.strip() for l in lines]

In [2]:
import numpy as np

In [3]:
def create_grid(lines):
    coords = [[tuple([int(n) for n in c.split(',')]) for c in l.split('~')] for l in lines]
    x_max = max([max((c[0][0]), c[1][0]) for c in coords])
    y_max = max([max((c[0][1]), c[1][1]) for c in coords])
    z_max = max([max((c[0][2]), c[1][2]) for c in coords])
    
    grid = np.zeros((x_max+1, y_max+1, z_max+1), np.int16)
    for i, c in enumerate(coords):
        c1 = np.array(c[0])
        c2 = np.array(c[1])
        delta = c2 - c1
        delta_mag = sum(abs(delta))
        assert sum([1 for d in delta if d == 0]) >= 2, "Expeced only 1 delta element to be non-zero."
        
        brick_parts = [c1]
        for d in range(delta_mag):
            brick_parts.append((c1+(d+1)*delta/delta_mag).astype(int))
        for b in brick_parts:
            grid[tuple(b)] = i+1
    return grid

def bricks_fall(grid):
    keep_trying = True
    counter = 0
    while keep_trying and counter < 100:
        counter += 1
        keep_trying = False
        for b in range(1, np.max(grid)+1):
            # try to lower each brick as far as possible (but leave z=0 empty, since that is ground)
            b_coords = np.argwhere(grid == b)
            brick_can_fall = True
            for bi in b_coords:
                if bi[2] > 1 and (grid[(bi[0], bi[1], bi[2]-1)] == 0 or grid[(bi[0], bi[1], bi[2]-1)] == b):
                    # This brick can potentially fall.
                    pass
                else:
                    brick_can_fall = False
                    break
            if brick_can_fall:
                keep_trying = True
                for bi in b_coords:
                    grid[(bi[0], bi[1], bi[2]-1)] = grid[tuple(bi)]
                    grid[tuple(bi)] = 0
    return grid

def count_stable_bricks(grid):
    stable_count = 0
    
    for b in range(1, np.max(grid)+1):
        temp_grid = grid.copy()
        b_coords = np.argwhere(temp_grid == b)
        print(b, b_coords)
        for bi in b_coords:
            print(bi)
            temp_grid[tuple(bi)] = 0
        print('voorbij')
        new_grid = bricks_fall(temp_grid)
        print('niet voorbij')
        if np.array_equal(temp_grid, new_grid):
            stable_count += 1
    return stable_count

grid = create_grid(lines)
grid = bricks_fall(grid)
count_stable_bricks(grid)

1 [[4 5 7]
 [5 5 7]]
[4 5 7]
[5 5 7]
voorbij
niet voorbij
2 [[  7   2 154]
 [  8   2 154]
 [  9   2 154]]
[  7   2 154]
[  8   2 154]
[  9   2 154]
voorbij
niet voorbij
3 [[2 3 3]
 [2 4 3]]
[2 3 3]
[2 4 3]
voorbij


KeyboardInterrupt: 

# Day 22 (2023-12-22), Exercise b

In [ ]:
abs(np.array((1,2,-3)))

In [ ]:
a = np.array((1,2,3))

In [ ]:
a

In [ ]:
a[0]